# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/wode0weiyi/HGAlertViewController.git'
source 'https://github.com/CocoaPods/Specs.git'

target '__ProjectName__' do
 
end
